export const config = {
  key_domain: 'domain',
  key_service_term: 'Service_Period',
  key_apartmentservice_url: 'ApartmentService_URL',
  key_bgstatus: 'BG_Status',
  confirmation_fullpathname: '/home/_confirm',
  confirmation_shortpathname: '_confirm',
  shortkey_role_cba: 'cba',
  shortkey_role_fu: 'fu',
  shortkey_role_csst: 'csst',
  shortkey_role_cssm: 'cssm',
  shortkey_email_verificationemailaddress: 'eventgen28',
  shortkey_email_welcometocsstorcssm: 'eventgen32',
  shortkey_email_forgotpassword: 'eventgen15',
  shortkey_email_welcometofu: 'eventgen31',
  shortkey_email_welcometocba: 'eventgen30',
  shortkey_email_senttocsst: 'eventgen14',
  shortkey_email_senttocssm: 'eventgen13',
  shortkey_email_newservice_senttocssm: 'eventgen23',
  shortkey_email_newservice_senttocsst: 'eventgen24',
  shortkey_email_newservice_senttocssmapproved: 'eventgen21',
  shortkey_email_newservice_senttocssmreject: 'eventgen22',
  shortkey_email_newservice_upgrade_senttocssm: 'eventgen33',
  shortkey_email_rejected: 'eventgen11',
  shortkey_email_approved: 'eventgen12',
  shortkey_bg_sentocsst: 'csst-bgcheck',
  user_rolecode_cba: 'CLIENT_BUSINESS_ADMINISTRATOR',
  user_rolecode_fu: 'FREELANCER_USER',
  user_rolecode_csct: 'CORE_SERVICE_SUPPORT_TEAM',
  user_rolecode_cscm: 'CORE_SERVICE_SUPPORT_MANAGER',
  user_rolecode_basicauth: 'W4U_BASIC_AUTHORIZATION',
  bg_code_approved: 'BG_APPROVED',
  bg_code_rejected: 'BG_REJECTED',
  bg_code_senttoccsm: 'BG_SENTTOCSSM',
  bg_code_senttoccst: 'BG_SENTTOCSST',
  bg_code_incompleteprofile: 'BG_INCOMPLETEPROFILE',
  bg_code_completedprofile: 'BG_COMPLETEDPROFILE',
  default_prefer_lang: 'en',
  lang_code_hi: 'hi',
  lang_code_te: 'te',
  lang_english_word: 'en-English',
  lang_hindi_word: 'hi-हिंदी',
  lang_telugu_word: 'te-తెలుగు',
  profiletype_avatar: 'avatar',
  profiletype_nationalid: 'nationalid',
  imgtype_png: 'image/png',
  imgtype_jpeg: 'image/jpeg',
  imgtype_jpg: 'image/jpg',
  imgtype_pdf: 'application/pdf',
  imgtype_zip: 'application/x-zip-compressed',
  GOOGLE_MAPS_API_KEY: 'AIzaSyBDDFawIBF3roB7RB1lI7g1D6qbn2e6oB4',
  newservice_code_senttocssm: 'SENT_TO_CSSM',
  newservice_code_senttocsst: 'SENT_TO_CSST',
  newservice_code_approved: 'APPROVED',
  newservice_code_rejected: 'REJECTED',
  category_code_A_S: 'A_S',
  category_code_FS_S: 'FS_S',
  domain_code_SE_P: 'SE_P',
  user_service_status_paymentpending_shortkey: 'payment-pending',
  user_service_status_paymentpending: 'PAYMENT_PENDING',
  user_service_status_published: 'PUBLISHED',
  user_service_status_paymentpaid: 'PAYMENT_PAID',
  refer_key_furegfee: 'FU_RegFee',
  fu_job_created_shortkey: 'fu-job-created',
  widget_logo: 'logoId',
  widget_companyimgurl: 'companyimgurlId',
  widget_companybgurlId: 'companybgurlId',
  shortkey_termsofservice_english: 'terms_eng',
  shortkey_termsofservice_telugu: 'terms_tel',
  shortkey_termsofservice_hindi: 'terms_hin',
  shortkey_privacypolicy_english: 'pp_english',
  shortkey_privacypolicy_telugu: 'pp_telugu',
  shortkey_privacypolicy_hindi: 'pp_hindi',
  banner_video1_en: 'video1en',
  banner_video2_en: 'video2en',
  banner_video1_te: 'video1te',
  banner_video2_te: 'video2te',
  banner_video1_hi: 'video1hi',
  banner_video2_hi: 'video2hi',
  rolecode_notification: 'TOASTER_FREELANCER_USER_ALL',
  rolecode_toast_notification_cba: 'TOASTER_CLIENT_BUSINESS_ADMINISTRATOR',
  payment_success: 'Success',
  voliation:'voliation',
  notifcationlist:'notifcationlist',
  escape:'Escape',
  enter: 'Enter',
  ArrowDown:'ArrowDown',
  ArrowUp:'ArrowUp'
};


